version: "3.9"
services:
  db:
    image: postgres:15
    container_name: learner_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: learner_portfolio
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./src/backend
    container_name: learner_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/learner_portfolio
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src/backend:/app

  frontend:
    build: ./src/frontend
    container_name: learner_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/usr/src/app
    command: ["npm", "start"]

volumes:
  db_data:
